// ============================================================================
// GAME 3: AI or Human? — 5 Complete Sets of 15 Questions (75 Questions)
// Players vote: [AI Generated] or [Human Made]
// Mixed media: Art, Code, Poetry, Philosophy, Conference Pitches & African Lore
// ============================================================================

// ----------------------------------------------------------------------------
// SET 1: The Frontier of Synthesis
// ----------------------------------------------------------------------------
const SET1 = [
  {
    mediaType: 'text',
    category: 'Poetry',
    prompt: 'Was this stanza written by a human poet or generated by an AI?',
    snippet: '"The autumn leaves are whispers in the chill,\nOld shadows stretching past the silent mill.\nA breath of smoke upon the violet air,\nAnd winter knocking before we are aware."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'Generated by Claude 3.5 Sonnet in 1.2 seconds when prompted for classical melancholic autumnal rhyme.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Philosophy Quote',
    prompt: 'Who formulated this philosophical milestone on machine cognition?',
    snippet: '"A computer would deserve to be called intelligent if it could deceive a human into believing that it was human."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Written by British mathematician Alan Turing in his historic 1950 paper "Computing Machinery and Intelligence".',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Game Engine Code',
    prompt: 'Is this legendary algorithm human-written or generated by an AI coding copilot?',
    snippet: 'float Q_rsqrt(float number) {\n  long i;\n  float x2, y;\n  const float threehalfs = 1.5F;\n  x2 = number * 0.5F;\n  y  = number;\n  i  = * ( long * ) &y;\n  i  = 0x5f3759df - ( i >> 1 ); // what the...?\n  y  = y * ( threehalfs - ( x2 * y * y ) );\n  return y;\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The iconic "Fast Inverse Square Root" algorithm from Quake III Arena (1999) featuring the famous magic constant 0x5f3759df.',
    timer: 15
  },
  {
    mediaType: 'image',
    category: 'Classical Oil Art',
    prompt: 'Was this painting created by a human classical master or generated by Midjourney?',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
    caption: 'Intricate oil still life with botanical realism and natural pigment balance',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Authentic European master still life from the Rijksmuseum heritage collection.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Conference Pitch',
    prompt: 'Is this opening address human-written or generated by an AI language model?',
    snippet: '"Welcome brilliant minds to GritinAI Connect 2.0! Where African ingenuity meets the frontier of artificial intelligence. We are not spectators in the digital revolution; we are the architects accelerating Africa\'s destiny from awareness into tangible economic impact."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Created with GPT-4o using a prompt for an inspirational opening rally for Benin City tech innovators.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'African Literature',
    prompt: 'Is this iconic opening line written by an African author or synthesized by an LLM?',
    snippet: '"Turning and turning in the widening gyre the falcon cannot hear the falconer; things fall apart; the centre cannot hold; mere anarchy is loosed upon the world."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Quoted by Chinua Achebe as the epigraph to his masterpiece "Things Fall Apart" (originally from W.B. Yeats).',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Python Data Science',
    prompt: 'Is this Python function handwritten by a senior engineer or synthesized by an AI assistant?',
    snippet: 'def compute_discounted_reward(rewards, gamma=0.99):\n    """Calculates discounted cumulative rewards."""\n    discounted = []\n    running_add = 0.0\n    for r in reversed(rewards):\n        running_add = r + gamma * running_add\n        discounted.insert(0, running_add)\n    return np.array(discounted)',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Generated by GitHub Copilot Chat when asked for a standard reinforcement learning policy gradient reward calculator.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Architectural Photography',
    prompt: 'Is this dramatic geometric skyline a real architectural photograph or AI rendered?',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    caption: 'Modernist concrete facade casting sharp directional sunlight shadows',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real architectural photograph captured on a Sony mirrorless camera in Milan.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Brand Tagline',
    prompt: 'Is this GritinAI brand value statement human authored or AI generated?',
    snippet: '"Dedication to our community guides the vision behind our products. We believe technology should strengthen local ecosystems, not replace them."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The official founding vision statement written by the GritinAI team on gritinai.com.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Haiku',
    prompt: 'Was this 5-7-5 syllable haiku composed by a human poet or generated by AI?',
    snippet: '"Code runs through the night,\nGreen cursor blinks on the screen,\nDawn drinks morning coffee."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Written by Google Gemini in zero-shot mode on the theme of late-night programming.',
    timer: 12
  },
  {
    mediaType: 'code',
    category: 'JavaScript Web Logic',
    prompt: 'Is this debounce utility handwritten by a developer or generated by AI?',
    snippet: 'function debounce(fn, ms) {\n  let timer;\n  return function(...args) {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn.apply(this, args), ms);\n  };\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The classic canonical JavaScript debounce function penned in human web utility libraries since 2012.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Studio Portrait',
    prompt: 'Is this human portrait an authentic photograph or generated by Midjourney v6?',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    caption: 'Close-up studio beauty shot with soft rim lighting and natural skin pores',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Authentic professional studio camera portrait on Unsplash with natural organic micro-imperfections.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Tech Startup Pitch',
    prompt: 'Was this pitch description human-written or synthesized by an AI tool?',
    snippet: '"Ubá integrates machine intelligence into frontline retail checkout, transforming simple cash transactions into real-time demand forecasts for neighborhood merchants across Nigeria."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The authentic product description for GritinAI’s Ubá smart inventory platform.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Philosophical Meditation',
    prompt: 'Was this reflection written by a human essayist or generated by AI?',
    snippet: '"To remember is not to pull a file from a cabinet, but to weave a fresh rug upon the loom of the present using threads stained by time."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Synthesized by Anthropic Claude 3.5 Sonnet when asked for an evocative metaphor on human episodic memory.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Python Algorithm',
    prompt: 'Is this recursive binary search handwritten by an educator or generated by an AI?',
    snippet: 'def binary_search(arr, low, high, x):\n    if high >= low:\n        mid = (high + low) // 2\n        if arr[mid] == x:\n            return mid\n        elif arr[mid] > x:\n            return binary_search(arr, low, mid - 1, x)\n        else:\n            return binary_search(arr, mid + 1, high, x)\n    return -1',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Classic computer science textbook implementation taught by educators for decades.',
    timer: 12
  }
];

// ----------------------------------------------------------------------------
// SET 2: African Tech, Culture & Cybernetic Creativity
// ----------------------------------------------------------------------------
const SET2 = [
  {
    mediaType: 'text',
    category: 'African Proverbs',
    prompt: 'Is this proverb authentic African folk wisdom or hallucinated by an AI?',
    snippet: '"The river that forgets its source will soon dry up in the harmattan."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: An ancient Yoruba/West African proverb honoring cultural roots and ancestry.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'African Proverbs',
    prompt: 'Is this proverb an authentic traditional saying or created by an AI?',
    snippet: '"A lizard that learns to fly like a bird will only break its belly on the stone."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Fabricated by ChatGPT when prompted to invent a plausible-sounding African proverb about staying humble.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'CSS Animation',
    prompt: 'Is this pulsing live indicator CSS written by a human UI engineer or generated by AI?',
    snippet: '@keyframes pulseLive {\n  0%, 100% { opacity: 1; transform: scale(1); }\n  50% { opacity: 0.45; transform: scale(1.15); }\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Custom CSS keyframe animation built by the GritinAI design team for live player indicators.',
    timer: 12
  },
  {
    mediaType: 'image',
    category: 'Fine Art / Bronze',
    prompt: 'Is this historic royal sculpture authentic African heritage or an AI 3D render?',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    caption: 'Antique cast bronze bust showcasing historical regal ceremonial attire',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Authentic museum photography of historical West African cast bronze heritage.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Keynote Abstract',
    prompt: 'Is this keynote summary written by an event organizer or an AI prompt?',
    snippet: '"In ‘The Catalyst Effect’, Mrs Olamide Efosa explores how micro-entrepreneurs in Benin City and across Nigeria can leverage generative AI models to multiply operational output and secure venture funding."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Summarized by an LLM based on speaker session themes for Connect 2.0.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Sci-Fi Prose',
    prompt: 'Was this cybernetic African city description penned by an author or AI?',
    snippet: '"Solar trams glided above the red clay walls of old Benin, their transparent glass rooftops capturing equatorial sunlight while algorithms tuned the market trade along Ring Road in silence."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Written by Claude 3.5 Sonnet when prompted for an African solarpunk vision of futuristic Benin City.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'JavaScript Event Bus',
    prompt: 'Is this simple pub/sub event emitter pattern human engineered or generated by AI?',
    snippet: 'class EventEmitter {\n  constructor() { this.events = {}; }\n  on(e, fn) { (this.events[e] = this.events[e] || []).push(fn); }\n  emit(e, ...data) { (this.events[e] || []).forEach(fn => fn(...data)); }\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Classic 6-line micro EventEmitter pattern human developers have shared on StackOverflow for years.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Nature & Landscape',
    prompt: 'Is this misty mountain landscape a real photograph or generated by Midjourney?',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
    caption: 'Dramatic rolling alpine mist over evergreen mountain slopes at sunrise',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real panoramic landscape photograph by human nature photographer Bailey Zindel.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Tech Testimonial',
    prompt: 'Is this testimonial quote from a real partner or generated by an LLM?',
    snippet: '"Partnering with GritinAI transformed our academy’s approach to digital education. Their team helped us launch an intelligent learning platform serving hundreds of students in record time."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real testimonial by Hope Omo, School Administrator at Torch Bearers Academy.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Philosophy / Ethics',
    prompt: 'Is this argument on algorithmic fairness human authored or AI generated?',
    snippet: '"An algorithm trained solely on historical records does not predict the future; it simply automates the prejudices of the past and christens them as objective truth."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Created by GPT-4 when asked to summarize machine learning bias in a single compelling aphorism.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'React Hook',
    prompt: 'Is this custom React hook written by a human developer or generated by AI?',
    snippet: 'function useOnlineStatus() {\n  const [isOnline, setIsOnline] = useState(navigator.onLine);\n  useEffect(() => {\n    const on = () => setIsOnline(true);\n    const off = () => setIsOnline(false);\n    window.addEventListener("online", on);\n    window.addEventListener("offline", off);\n    return () => {\n      window.removeEventListener("online", on);\n      window.removeEventListener("offline", off);\n    };\n  }, []);\n  return isOnline;\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Official example hook from the React.dev documentation written by the human React core docs team.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Cyberpunk Concept Art',
    prompt: 'Was this illuminated neon cybernetic street visual captured by a human camera or AI rendered?',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    caption: 'Neon turquoise and violet streaks through an electric city nightscape',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real human long-exposure night photography with light trails in Tokyo.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Micro-Essay',
    prompt: 'Was this micro-essay on African developer resilience written by a human or AI?',
    snippet: '"In Lagos and Benin, power fluctuates and bandwidth is dear, yet developers ship global-tier software from battery backups. Resource constraint is not a barrier; it is the crucible of our engineering grit."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Generated by Claude 3.5 Sonnet for a prompt celebrating West African tech developer resilience.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Poetry',
    prompt: 'Was this short poem written by a human or synthesized by AI?',
    snippet: '"Out of the night that covers me,\nBlack as the pit from pole to pole,\nI thank whatever gods may be\nFor my unconquerable soul."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The opening stanza of "Invictus" written by William Ernest Henley in 1875.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'SQL Query',
    prompt: 'Is this analytical SQL query handwritten by a data analyst or generated by an AI tool?',
    snippet: 'SELECT \n    DATE_TRUNC(\'month\', created_at) AS active_month,\n    COUNT(DISTINCT user_id) AS monthly_active_users,\n    SUM(amount) AS gross_revenue\nFROM transactions\nWHERE status = \'completed\'\nGROUP BY 1\nORDER BY 1 DESC;',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Standard human data analytics SQL template used by growth analysts worldwide.',
    timer: 14
  }
];

// ----------------------------------------------------------------------------
// SET 3: Code, Prose & The Intelligence Illusion
// ----------------------------------------------------------------------------
const SET3 = [
  {
    mediaType: 'text',
    category: 'Conference Announcement',
    prompt: 'Is this speaker announcement human-written or generated by AI?',
    snippet: '"From Code to Career: Leveraging AI to Drive African Youth Employment. Join Mrs Mary Okonkwo at GritinAI Connect 2.0 as she breaks down the essential skills bridging modern graduates into high-value global AI roles."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Official program copy published on the GritinAI Connect 2.0 speaker lineup.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Sci-Fi Dialogue',
    prompt: 'Is this machine dialogue human-scripted or generated by an AI?',
    snippet: '"I\'ve seen things you people wouldn\'t believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhäuser Gate. All those moments will be lost in time, like tears in rain."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The immortal "Tears in Rain" monologue delivered by Rutger Hauer in Blade Runner (1982).',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Machine Learning Boilerplate',
    prompt: 'Is this PyTorch training loop handwritten by an engineer or generated by AI?',
    snippet: 'for epoch in range(num_epochs):\n    model.train()\n    for batch_x, batch_y in dataloader:\n        optimizer.zero_grad()\n        outputs = model(batch_x)\n        loss = criterion(outputs, batch_y)\n        loss.backward()\n        optimizer.step()',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: The textbook generic PyTorch loop generated identically by virtually all coding LLMs in 0.5s.',
    timer: 12
  },
  {
    mediaType: 'image',
    category: 'Sculpture & Pottery',
    prompt: 'Is this hand-thrown ceramic art genuine human pottery or AI rendered?',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&auto=format&fit=crop&q=80',
    caption: 'Earthy ceramic stoneware showing wheel grooves and glaze drip texture',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real artisan clay pottery shaped on a kick-wheel by an independent potter.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Product Description',
    prompt: 'Is this product description from an authentic app or hallucinated by AI?',
    snippet: '"Rapid is an AI prototyping platform designed to help technical and non-technical teams bridge the gap between idea and interactive demonstration in minutes."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The authentic product copy from rapid.gritinai.com.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'African Parable',
    prompt: 'Is this parable genuine African lore or AI hallucination?',
    snippet: '"When the elephant stepped upon the python’s tail, the tortoise smiled and said, ‘At last the king has found a carpet that moves.’"',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Fabricated by GPT-4 when asked to create a witty traditional animal fable.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Security Crypto',
    prompt: 'Is this password hashing snippet human-coded or AI generated?',
    snippet: 'const bcrypt = require("bcrypt");\nconst saltRounds = 12;\nasync function hashPassword(plainText) {\n  const salt = await bcrypt.genSalt(saltRounds);\n  return await bcrypt.hash(plainText, salt);\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Standard human security boilerplate recommended in Node.js bcrypt guides.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Macro Wildlife',
    prompt: 'Is this striking macro insect photograph authentic camera work or AI generated?',
    image: 'https://images.unsplash.com/photo-1551085254-e96b210db58a?w=800&auto=format&fit=crop&q=80',
    caption: 'Extreme close-up of butterfly wing scales displaying iridescent structural colors',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Award-winning real macro optics photography by human photographer Krzysztof Niewolny.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Philosophy of Mind',
    prompt: 'Who penned this critique of machine consciousness?',
    snippet: '"Imagine a native English speaker who knows no Chinese locked in a room full of boxes of Chinese symbols, using an English rulebook to manipulate them. He does not understand Chinese; he merely simulates understanding."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The famous "Chinese Room" thought experiment written by American philosopher John Searle in 1980.',
    timer: 15
  },
  {
    mediaType: 'text',
    category: 'Modern Poetry',
    prompt: 'Was this poignant poem written by a human or synthesized by an AI?',
    snippet: '"Silicon veins pulse with phantom light,\nDreaming of rivers it never has seen.\nWe taught it to count every star in the night,\nYet it sleeps in the dark of a flickering screen."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Written by Claude 3.5 Sonnet on the poetic melancholy of artificial neural networks.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Sorting Algorithm',
    prompt: 'Is this Python QuickSort implementation human written or generated by AI?',
    snippet: 'def quicksort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    middle = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + middle + quicksort(right)',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The canonical Pythonic 6-line QuickSort authored in standard Python documentation.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Urban Geometry',
    prompt: 'Is this high-rise staircase photograph real or synthetic Midjourney art?',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    caption: 'Spiral concrete staircase descending in a hypnotic logarithmic curve',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real architectural photography captured inside a monument in Berlin.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Mission Manifesto',
    prompt: 'Was this manifesto statement written by a conference committee or generated by AI?',
    snippet: '"Building on the success of GritinAI Connect 1.0 (2025), this edition moves beyond awareness to action — accelerating AI adoption for sustainable economic growth across Nigeria."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Authentic mission statement from the GritinAI Connect 2.0 website metadata.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'LinkedIn Thought Leadership',
    prompt: 'Is this LinkedIn post human-written or generated by an AI writing assistant?',
    snippet: '"🚀 Thrilled to announce that we are leveling up our AI stack! In today’s hyper-connected landscape, agility is everything. Remember: AI won’t replace you, but a professional using AI will. Agree? Thoughts in the comments! 👇"',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Classic ChatGPT LinkedIn template mimicking corporate influencer buzzwords.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Math / Geometry',
    prompt: 'Is this Manhattan distance calculation human written or generated by AI?',
    snippet: 'def manhattan_distance(p1, p2):\n    """Calculate L1 norm between two coordinate points."""\n    return sum(abs(a - b) for a, b in zip(p1, p2))',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Written by human Python algorithm developers using idiomatic zip generator syntax.',
    timer: 12
  }
];

// ----------------------------------------------------------------------------
// SET 4: Words, Logic & Machine Aesthetics
// ----------------------------------------------------------------------------
const SET4 = [
  {
    mediaType: 'text',
    category: 'Literature Quote',
    prompt: 'Was this unforgettable phrase written by an African novelist or generated by AI?',
    snippet: '"The sun whose rays are all-embracing does not care whether the tree that receives its warmth is crooked or straight."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Proverb woven into human African oral literature and classical novels.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'AI Motivational Pitch',
    prompt: 'Was this startup rally written by a human or generated by an AI copilot?',
    snippet: '"To every builder in Edo State holding an idea tonight: the cloud doesn’t know where you were born, only what you deploy. Write the code, train the model, claim your future."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Created by Claude 3.5 Sonnet when prompted for an inspiring speech line for young Benin City founders.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Frontend Performance',
    prompt: 'Is this IntersectionObserver lazy loader written by a human or generated by AI?',
    snippet: 'const observer = new IntersectionObserver((entries, obs) => {\n  entries.forEach(entry => {\n    if (entry.isIntersecting) {\n      const img = entry.target;\n      img.src = img.dataset.src;\n      obs.unobserve(img);\n    }\n  });\n});',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Standard human web performance pattern from MDN Web Docs.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Abstract Oil Canvas',
    prompt: 'Is this abstract expressionist painting human-created or synthesized by DALL-E 3?',
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80',
    caption: 'Vibrant impasto swirls of acrylic and oil paint with physical knife ridges',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real acrylic canvas painted with palette knives by human artist Steve Johnson.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Workshop Overview',
    prompt: 'Is this workshop description authentic event copy or AI generated?',
    snippet: '"Build with Rapid: Join Peter Nnachor in Workshop Track A as attendees go from zero to a functioning AI application prototype in under 90 minutes."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Official session description from the GritinAI Connect 2.0 schedule.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'African Proverbs',
    prompt: 'Is this an authentic Nigerian proverb or generated by AI?',
    snippet: '"No matter how long the night is, the rooster does not crow until dawn arrives."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Authentic West African folk proverb about patience and divine timing.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Python Matrix Math',
    prompt: 'Is this dot-product implementation human written or generated by AI?',
    snippet: 'def matrix_vector_mult(matrix, vector):\n    return [\n        sum(m_val * v_val for m_val, v_val in zip(row, vector))\n        for row in matrix\n    ]',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Created by GitHub Copilot when asked for pure Python matrix multiplication without NumPy.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Astrophotography',
    prompt: 'Is this deep sky photograph of the Milky Way real or an AI generation?',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    caption: 'Long exposure of galactic dust lanes over a silhouette desert ridge',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real astronomical long-exposure photograph taken in the Atacama Desert.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Scientific Philosophy',
    prompt: 'Who wrote this famous sentence on the nature of cosmos and science?',
    snippet: '"Somewhere, something incredible is waiting to be known."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Widely attributed to celebrated astronomer Carl Sagan in describing scientific wonder.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Corporate Vision',
    prompt: 'Was this corporate mission drafted by a founder or generated by AI?',
    snippet: '"We design and deploy AI platforms, operational systems, and smart infrastructure products built to boost local business growth across Africa."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Direct headline from the homepage of gritinai.com.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Data Structures',
    prompt: 'Is this linked list node class written by a human or generated by an AI?',
    snippet: 'class Node:\n    def __init__(self, data):\n        self.data = data\n        self.next = None\n\nclass LinkedList:\n    def __init__(self):\n        self.head = None',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Standard university computer science introductory linked list implementation.',
    timer: 12
  },
  {
    mediaType: 'image',
    category: 'Street Life',
    prompt: 'Is this candid street portrait real or synthesized by an AI diffusion model?',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    caption: 'Spontaneous candid smile with authentic environmental depth of field',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real candid photograph capturing genuine human emotion on a 50mm f/1.8 lens.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Micro-Poem',
    prompt: 'Was this 2-line couplet written by a poet or generated by AI?',
    snippet: '"The clock does not tick away the hours;\nIt simply counts the petals falling from our powers."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Created by Claude 3.5 Sonnet when prompted for a bittersweet rhyme about mortality.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Tech Job Description',
    prompt: 'Is this tech job requirement human-written or drafted by ChatGPT?',
    snippet: '"Must possess 10+ years of production experience in Prompt Engineering, Transformers (published in 2017), and fine-tuning Llama 3 models."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: A humorous hallucination highlighting impossible timelines (Transformers was only invented 9 years ago!).',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Algorithm / Math',
    prompt: 'Is this Greatest Common Divisor function human-coded or AI created?',
    snippet: 'def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Euclid’s 2,300-year-old algorithm written in concise human Python.',
    timer: 12
  }
];

// ----------------------------------------------------------------------------
// SET 5: The Grand Synthesis
// ----------------------------------------------------------------------------
const SET5 = [
  {
    mediaType: 'text',
    category: 'African Proverbs',
    prompt: 'Is this an authentic African proverb or generated by an AI?',
    snippet: '"Wisdom is like a baobab tree; no one individual can embrace it all with both hands."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Renowned traditional Ghanaian/Ewe proverb on the boundless nature of knowledge.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Conference Theme',
    prompt: 'Is this event tagline human-crafted or AI synthesized?',
    snippet: '"From Awareness to Action: Accelerating Africa’s Digital Economy with AI."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The official guiding rally of GritinAI Connect 2.0.',
    timer: 12
  },
  {
    mediaType: 'code',
    category: 'API Integration',
    prompt: 'Is this fetch request snippet human-written or generated by AI?',
    snippet: 'async function fetchLiveLeaderboard() {\n  const res = await fetch("/api/leaderboard");\n  if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);\n  return await res.json();\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Standard human web API consumer pattern with error check.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Sculpture & Texture',
    prompt: 'Is this carved stone surface an authentic museum sculpture or Midjourney generation?',
    image: 'https://images.unsplash.com/photo-1544717302-de2939b7ef71?w=800&auto=format&fit=crop&q=80',
    caption: 'Weathered limestone relief showing authentic millennia-old chisel marks',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Genuine historical stone bas-relief photographed in an archaeological museum.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Future Vision',
    prompt: 'Was this vision statement written by a founder or synthesized by an AI?',
    snippet: '"The next great foundation model will not be trained solely on Silicon Valley blogs; it will learn from African market ledgers, oral dialects, and agrarian rhythms that defy western assumptions."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Crafted by Claude 3.5 Sonnet when prompted for an inspiring future of decentralized African AI.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Poetic Reflection',
    prompt: 'Was this poetic meditation written by a human or generated by AI?',
    snippet: '"We thought the machines would take the factories first,\nFreeing our hands to paint and rhyme.\nInstead they paint the sky before our thirst,\nWhile we still punch the clocks of time."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Created by GPT-4 on the paradox of generative AI replacing creative arts before physical labor.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Python Logic',
    prompt: 'Is this palindrome checker written by a human or generated by AI?',
    snippet: 'def is_palindrome(s):\n    cleaned = "".join(ch.lower() for ch in s if ch.isalnum())\n    return cleaned == cleaned[::-1]',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Idiomatic human Python solution taught in introductory programming courses.',
    timer: 12
  },
  {
    mediaType: 'image',
    category: 'Fine Art / Water Color',
    prompt: 'Is this delicate watercolor floral artwork authentic human painting or AI generated?',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    caption: 'Soft watercolor wash with authentic pigment bleeding and wet-on-wet pooling',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Authentic watercolor painting exhibiting genuine water capillary action on rag paper.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Tech Impact Quote',
    prompt: 'Is this client quote authentic human feedback or generated by AI?',
    snippet: '"GritinAI has become our most trusted partner for delivering technology to clients. Their collaborative process and understanding of local business needs let us deploy sophisticated solutions quickly."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Authentic testimonial by Joseph Origho, CEO of Ceroxx Technologies on gritinai.com.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'African Proverbs',
    prompt: 'Is this an authentic traditional proverb or generated by an AI?',
    snippet: '"When two elephants fight, it is the grass beneath their feet that suffers."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Ancient East and West African proverb on the consequences of conflict on innocent communities.',
    timer: 12
  },
  {
    mediaType: 'code',
    category: 'JavaScript Functional',
    prompt: 'Is this array unique filter human written or generated by AI?',
    snippet: 'const unique = arr => [...new Set(arr)];',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The canonical ES6 spread-Set idiom shared millions of times by human web developers.',
    timer: 10
  },
  {
    mediaType: 'image',
    category: 'Architectural Shadow',
    prompt: 'Is this minimalist architectural detail real photography or AI rendered?',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    caption: 'Towering glass curtain wall reflecting midday sky gradients',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Real photograph of modern skyscraper glass facades by human photographer Sean Pollock.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Philosophy / AI',
    prompt: 'Who originally stated this foundational warning about computers?',
    snippet: '"The danger of computers is not that they will become intelligent and take over the world, but that they will become so foolish and we will still obey them."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: Formulated by computer scientist and pioneer Sydney J. Harris.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'African Parable',
    prompt: 'Is this witty saying real African folklore or AI synthesized?',
    snippet: '"The monkey who learns to wear sunglasses will still blink when the sun sets behind the hills."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI generated: Created by GPT-4o when prompted to invent a proverb about surface vanity.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Machine Learning Loss',
    prompt: 'Is this Mean Squared Error loss function human written or AI generated?',
    snippet: 'def mse_loss(y_true, y_pred):\n    return sum((yt - yp) ** 2 for yt, yp in zip(y_true, y_pred)) / len(y_true)',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human made: The standard textbook human formulation of MSE in pure Python.',
    timer: 12
  }
];

module.exports = {
  set1: SET1,
  set2: SET2,
  set3: SET3,
  set4: SET4,
  set5: SET5
};
