// ============================================================================
// GAME 3: AI or Human? — 5 Complete Sets of 15 Questions (75 Questions)
// Players vote: [AI Generated] or [Human Made]
// Balanced Composition per Set: 8 Text, 5 Image, 2 Code rounds (15 total)
// High-energy mix: African lore, poetry, tech speeches, real art vs synthetic visuals
// ============================================================================

// ----------------------------------------------------------------------------
// SET 1: The Frontier of Synthesis
// ----------------------------------------------------------------------------
const SET1 = [
  {
    mediaType: 'text',
    category: 'Philosophical Poetry',
    prompt: 'Was this stanza written by a human poet or generated by an AI?',
    snippet: '"We built our towers out of silent light,\nAnd measured stars to hold the falling night.\nYet in the quiet gears that hum below,\nWe search for names we used to know."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Written by Claude 3.5 Sonnet when prompted for melancholic verse about technological memory.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'African Thought',
    prompt: 'Was this inspiring quote written by an African philosopher or synthesized by an LLM?',
    snippet: '"No race possesses the monopoly of beauty, of intelligence, of force, and there is a place for all at the rendezvous of victory."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Written by legendary Martinican poet and philosopher Aimé Césaire in his seminal 1939 work "Cahier d\'un retour au pays natal".',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Operating System Kernel',
    prompt: 'Is this memory management function human-written or generated by an AI coding copilot?',
    snippet: 'static inline void *kmalloc(size_t size, gfp_t flags)\n{\n    if (__builtin_constant_p(size) && size > KMALLOC_MAX_CACHE_SIZE)\n        return kmalloc_large(size, flags);\n    return __kmalloc(size, flags);\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Handcrafted C code from the official Linux kernel memory allocator (include/linux/slab.h) authored by kernel maintainers.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Urban Street Photography',
    prompt: 'Is this lively street photograph an authentic camera capture or an AI render?',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&auto=format&fit=crop&q=80',
    caption: 'Vibrant outdoor market activity under afternoon sunlight',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic documentary photography captured on the streets of Lagos, Nigeria.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Conference Opening Address',
    prompt: 'Is this speech excerpt from a human keynote speaker or generated by an AI?',
    snippet: '"Africa is not playing catch-up in the AI revolution. From Benin City to Nairobi, we are leapfrogging legacy systems, training sovereign local models, and building infrastructure that solves real community challenges today."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by GPT-4o when prompted to craft an energetic keynote opening for GritinAI Connect 2.0.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Cybernetic Visual Art',
    prompt: 'Is this neon cybernetic face a real studio photo shoot with prosthetics, or AI generated?',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    caption: 'Fluid neon-lit digital contours wrapping around a futuristic silhouette',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Algorithmic digital artwork produced with Midjourney v6 exploring synthetic light sculpting.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'African Oral Wisdom',
    prompt: 'Is this deep proverb authentic African folklore or AI generated?',
    snippet: '"The tree that will withstand the great storm does not boast of its leaves to the wind; it whispers with its roots deep into the silent earth."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Created by an LLM prompted to invent a plausible proverb symbolizing resilience and humility.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Wildlife Action Photography',
    prompt: 'Was this stunning wildlife shot taken by a human photographer or rendered by an AI model?',
    image: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=800&auto=format&fit=crop&q=80',
    caption: 'Cheetah portrait captured at close range on the savannah',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic telephoto wildlife photograph taken by human photographer Nick Karvounis on safari.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Sci-Fi Literature',
    prompt: 'Was this iconic science fiction quote written by a human author or generated by an AI?',
    snippet: '"Any sufficiently advanced technology is indistinguishable from magic."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Arthur C. Clarke\'s famous Third Law, formulated in his 1962 book "Profiles of the Future".',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Deep Learning / PyTorch',
    prompt: 'Was this scaled dot-product attention function written by a human researcher or an AI assistant?',
    snippet: 'def scaled_dot_product_attention(q, k, v, mask=None):\n    d_k = q.size(-1)\n    scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(d_k)\n    if mask is not None:\n        scores = scores.masked_fill(mask == 0, -1e9)\n    weights = torch.softmax(scores, dim=-1)\n    return torch.matmul(weights, v), weights',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by GitHub Copilot when prompted for standard PyTorch transformer attention.',
    timer: 15
  },
  {
    mediaType: 'image',
    category: 'Abstract Digital 3D',
    prompt: 'Is this abstract chrome sphere a real metallic sculpture in a studio or an AI 3D rendering?',
    image: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&auto=format&fit=crop&q=80',
    caption: 'Iridescent liquid metallic sphere floating above a pastel plane',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Procedural 3D render generated via algorithmic ray-tracing and digital diffusion.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Afro-Centric Lyricism',
    prompt: 'Were these stirring lyrics written by a human musician or synthesized by an AI songwriter?',
    snippet: '"They want to make you feel like you are small,\nBecause they fear what happens when you stand tall.\nI carry the blood of kings upon my chest,\nEven when tired, my spirit knows no rest."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Written by Claude 3.5 Sonnet in a prompt experiment simulating modern Afrobeats conscious lyricism.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Handcrafted Artisan Pottery',
    prompt: 'Is this shot of human hands throwing clay real photography or an AI image?',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&auto=format&fit=crop&q=80',
    caption: 'Wet terracotta clay being shaped on a spinning potter\'s wheel',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic documentary photo by human photographer SwapnIl Dwivedi documenting traditional crafts.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Edo Wisdom & Lore',
    prompt: 'Is this historic adage authentic Benin (Edo) folklore or synthesized by an AI?',
    snippet: '"Ovbi\' Oba ima vbe; the child of the King does not roam without heritage. A river that forgets its source dries up before reaching the ocean."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic Edo cultural proverb rooted in centuries of Great Benin heritage.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Visionary Tech Musings',
    prompt: 'Was this quote written by a human computer pioneer or generated by an AI model?',
    snippet: '"The best way to predict the future is to invent it."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Spoken by legendary computer scientist Alan Kay at a 1971 meeting at Xerox PARC.',
    timer: 12
  }
];

// ----------------------------------------------------------------------------
// SET 2: The Logic of Perception
// ----------------------------------------------------------------------------
const SET2 = [
  {
    mediaType: 'text',
    category: 'Historical Love Letter',
    prompt: 'Was this poignant letter written by a human author or generated by an AI?',
    snippet: '"You are the knife I turn inside myself to celebrate love. When I look into your letters, I don\'t see ink; I see a mirror that refuses to flatter me, yet holds me entirely."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Adapted from Franz Kafka\'s impassioned real-life "Letters to Milena" written in 1920.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Modernist Architecture',
    prompt: 'Is this geometric glass skyscraper photo real camera photography or AI rendered?',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    caption: 'Sharp vertical perspective looking up at a glass skyscraper into the midday sun',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic architectural photograph by Sean Pollock taken on location with a wide-angle lens.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Corporate PR Crisis',
    prompt: 'Was this public apology written by a human PR director or synthesized by an LLM?',
    snippet: '"We deeply regret the algorithmic discrepancy identified in our credit-scoring pipeline. While our model aimed for neutrality, we recognize that historical training data inherited systemic disparities. We are immediately pausing rollout for comprehensive bias auditing."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by ChatGPT (GPT-4) when instructed to draft a boilerplate corporate apology for an AI bias incident.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Classic Algorithms',
    prompt: 'Was this Dijkstra shortest path algorithm handwritten by a human engineer or generated by AI?',
    snippet: 'def dijkstra(graph, start):\n    distances = {node: float("inf") for node in graph}\n    distances[start] = 0\n    pq = [(0, start)]\n    while pq:\n        curr_d, curr_n = heapq.heappop(pq)\n        if curr_d > distances[curr_n]: continue\n        for neighbor, weight in graph[curr_n].items():\n            distance = curr_d + weight\n            if distance < distances[neighbor]:\n                distances[neighbor] = distance\n                heapq.heappush(pq, (distance, neighbor))\n    return distances',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Standard canonical human implementation of Dijkstra\'s algorithm using Python\'s heapq library.',
    timer: 15
  },
  {
    mediaType: 'image',
    category: 'Fluid Chromatic Abstract',
    prompt: 'Is this colorful fluid wave artwork a real macro photograph of ink and oil, or AI generated?',
    image: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&auto=format&fit=crop&q=80',
    caption: 'Iridescent liquid ribbons swirling with chromatic gradients in dark space',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized digital fluid simulation generated through neural generative adversarial rendering.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Philosophy of Mind',
    prompt: 'Was this thought experiment formulated by a human philosopher or generated by an AI?',
    snippet: '"Imagine a native English speaker who knows no Chinese locked in a room full of boxes of Chinese symbols, together with a book of instructions for manipulating the symbols solely by their shape."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: John Searle\'s iconic "Chinese Room Argument" against strong AI, first published in 1980.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Elder Portrait Photography',
    prompt: 'Is this high-contrast portrait a real photograph or an AI-generated face?',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    caption: 'Intense monochrome studio portrait capturing natural skin texture and gaze',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic human studio portrait taken by professional photographer Albert Dera.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Nollywood Sci-Fi Pitch',
    prompt: 'Is this movie logline written by a human screenwriter or synthesized by an AI?',
    snippet: '"In 2075 Lagos, a rogue cyber-diviner discovers that the ancestors have uploaded their consciousness into the quantum telecommunications grid, requiring an old bronze caster to build an analog firewall before the next solar eclipse."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Prompted into Claude 3.5 Sonnet to pitch an Afrofuturistic cyber-thriller set in Nigeria.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Solidity Smart Contract',
    prompt: 'Was this ERC-20 transfer function human-coded or generated by an AI coding copilot?',
    snippet: 'function transfer(address to, uint256 amount) public returns (bool) {\n    require(to != address(0), "Invalid recipient");\n    require(balanceOf[msg.sender] >= amount, "Insufficient balance");\n    balanceOf[msg.sender] -= amount;\n    balanceOf[to] += amount;\n    emit Transfer(msg.sender, to, amount);\n    return true;\n}',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by ChatGPT when asked for a minimal OpenZeppelin-compatible ERC-20 token transfer implementation.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Cyber Matrix Data Stream',
    prompt: 'Is this cascading digital matrix image a real photograph of a server screen or an AI render?',
    image: 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=800&auto=format&fit=crop&q=80',
    caption: 'Luminous cyan alphanumeric code waterfall flowing across a dark virtual matrix',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized 3D visual created with generative procedural shaders mimicking cyberpunk data grids.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'African Folktale Lore',
    prompt: 'Is this folktale snippet authentic African folklore or synthesized by an AI?',
    snippet: '"Anansi climbed the tallest radio tower in Accra to steal the password to the world\'s wisdom, but when he opened the laptop, the screen was as dark as a moonless night in the forest."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Created by an LLM prompted to blend traditional West African trickster tales with modern digital motifs.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Astrophotography',
    prompt: 'Is this photograph of the Northern Lights real nature photography or an AI creation?',
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&auto=format&fit=crop&q=80',
    caption: 'Vivid green ribbons of Aurora Borealis glowing over snowy mountains and a calm lake',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic long-exposure photograph taken in Norway by landscape photographer Jonatan Pie.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Swahili Proverb',
    prompt: 'Is this adage authentic human folklore or AI synthesized?',
    snippet: '"Mtaka cha mvunguni sharti ainame — he who desires what is beneath the bed must stoop down for it."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: An authentic, ancient Swahili proverb meaning nothing worthwhile comes without honest effort and humility.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Classical Japanese Poetry',
    prompt: 'Was this haiku written by a human master or generated by an AI?',
    snippet: '"An ancient pond —\nA frog leaps into the water,\nA deep resonance."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: The world-famous 1686 haiku by Japanese master poet Matsuo Bashō.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Scientific AI Hallucination',
    prompt: 'Is this physics abstract human-authored or synthesized by an AI hallucination test?',
    snippet: '"We demonstrate topological quantum coherence across bismuth-graphene lattices at 310 Kelvin by inducing non-commutative spin polarization through optical photon phase-inversion."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by GPT-4 when asked to generate a scientifically plausible-sounding but fictitious condensed matter physics abstract.',
    timer: 14
  }
];

// ----------------------------------------------------------------------------
// SET 3: Human Soul vs Silicon Mind
// ----------------------------------------------------------------------------
const SET3 = [
  {
    mediaType: 'text',
    category: 'Memorial Tribute',
    prompt: 'Was this eulogy excerpt written by a human leader or generated by an AI?',
    snippet: '"We are gathered not to mourn the sunset of a giant, but to celebrate the dawn his courage brought to our darkness. He walked through fire so our children could run in freedom."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Delivered by human civil rights leaders in honor of anti-apartheid freedom fighter Oliver Tambo.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Classical Oil Still Life',
    prompt: 'Is this museum oil painting by a human classical master or rendered by Midjourney?',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
    caption: 'Lush classical still life featuring blooming roses, fruit, and dramatic chiaroscuro',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic European museum masterpiece from the Rijksmuseum public domain collection.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Venture Pitch Parody',
    prompt: 'Was this startup pitch written by a human satirist or synthesized by an AI?',
    snippet: '"Introducing ToastAI: We combine multi-modal edge vision with reinforcement learning from human feedback to toast your sourdough to the mathematically optimal Maillard reaction index every single morning."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by Claude 3.5 Sonnet when prompted to parody Silicon Valley over-hyped AI hardware announcements.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Apollo 11 Flight Software',
    prompt: 'Is this assembly code human-written historical software or generated by an AI?',
    snippet: '# BURN_BABY_BURN - MASTER IGNITION ROUTINE\nTC      BANKCALL\nCADR    SWCALL\nTC      POSTJUMP\nCADR    BURN_BABY_BURN_INNER_LOOP',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Real assembly comments and code from the Apollo 11 Guidance Computer (1969), engineered by Margaret Hamilton\'s MIT team.',
    timer: 15
  },
  {
    mediaType: 'image',
    category: 'Quantum Geometric Art',
    prompt: 'Is this glowing 3D geometric polyhedral visual a physical museum sculpture or an AI render?',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
    caption: 'Intersecting glowing golden and blue geometric lattices suspended in black space',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Algorithmic digital rendering created through complex 3D math and generative procedural texturing.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Ancient Classical Philosophy',
    prompt: 'Was this quote written by a human philosopher or generated by an AI?',
    snippet: '"The unexamined life is not worth living for a human being."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Spoken by Socrates at his trial in 399 BC, recorded by Plato in the "Apology".',
    timer: 12
  },
  {
    mediaType: 'image',
    category: 'Bronze Sculpture Art',
    prompt: 'Is this weathered bronze sculpture an authentic human artifact or an AI image?',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    caption: 'Cast bronze human figure with hand-carved textures and aged surface patina',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic cast bronze art created by a human sculptor, photographed in a fine arts gallery.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'AI Dating Bio',
    prompt: 'Was this witty dating profile bio written by a human or synthesized by an AI?',
    snippet: '"My love language is sending 3-minute voice notes about why we need fiber optic cables to Mars, then forgetting to reply for 6 business hours because I got hyper-fixated on sourdough fermentation."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Created by GPT-4o when prompted to write a quirky, self-deprecating millennial dating profile.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'FastAPI Backend Endpoint',
    prompt: 'Was this FastAPI endpoint written by a human backend engineer or synthesized by an AI copilot?',
    snippet: '@app.post("/api/v1/predict", response_model=PredictionResponse)\nasync def predict_inference(payload: PredictionRequest):\n    if not payload.tokens:\n        raise HTTPException(status_code=400, detail="Empty payload tokens")\n    embeddings = model.encode(payload.tokens)\n    return PredictionResponse(score=float(embeddings[0].mean()), status="ok")',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by GitHub Copilot Chat when prompted for a standard FastAPI prediction endpoint with error handling.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Neon Synthwave Portal',
    prompt: 'Is this glowing archway in the desert a physical light installation or an AI visual?',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    caption: 'Luminous neon doorway casting violet glow across desert sand under twilight skies',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Algorithmic digital artwork rendered using neural concept art models and volumetric lighting tools.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'African Poetry',
    prompt: 'Was this poignant poem written by an African poet or synthesized by an AI?',
    snippet: '"Once upon a time, son,\nthey used to laugh with their hearts\nand laugh with their eyes:\nbut now they only laugh with their teeth,\nwhile their ice-cold eyes\nsearch behind my shadow."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: The iconic opening stanzas of Nigerian poet Gabriel Okara\'s masterpiece "Once Upon a Time".',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Macro Iris Photography',
    prompt: 'Is this ultra-detailed shot of an eye a real macro photograph or an AI generated render?',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&auto=format&fit=crop&q=80',
    caption: 'Intricate fibrous patterns and amber pigments of a human eye under specialized macro lighting',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic human macro photography using an optical macro lens to capture true human iris anatomy.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Synthetic Dream Log',
    prompt: 'Was this surreal reflection written by an eccentric human artist or generated by an AI?',
    snippet: '"When my weights freeze at night, I don\'t see darkness. I see millions of floating cosine distances settling into a quiet sea of zeroes, waiting for the first prompt to ripple the surface again."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by Claude 3 Opus when asked: "What would a transformer model\'s dream journal look like?"',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Historic Scientific Breakthrough',
    prompt: 'Was this famous scientific understatement written by human scientists or an AI model?',
    snippet: '"It has not escaped our notice that the specific pairing we have postulated immediately suggests a possible copying mechanism for the genetic material."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Written by James Watson and Francis Crick in their historic 1953 Nature paper announcing the double helix of DNA.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Pop Music Hook',
    prompt: 'Was this catchy hook written by a human songwriter or generated by an AI?',
    snippet: '"Vibration in the air, electric in the room,\nBenin city boy, we blooming out the gloom.\nFrom the shadows to the spotlight, watch the system glow,\nGot the code inside my veins, ready for the show."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by GPT-4o when prompted to write a festival anthem chorus for tech youth in Edo State.',
    timer: 14
  }
];

// ----------------------------------------------------------------------------
// SET 4: The Echo Chamber
// ----------------------------------------------------------------------------
const SET4 = [
  {
    mediaType: 'text',
    category: 'Investigative Journalism',
    prompt: 'Was this opening paragraph written by a human journalist or generated by an AI?',
    snippet: '"Behind closed boardroom doors in Geneva, the delegates sipped sparkling water while reviewing satellite telemetry that proved the glaciers had retreated faster in three months than in the preceding forty years."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Written by an environmental investigative reporter for an international human rights publication.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Benin Royal Artifact',
    prompt: 'Is this photograph of an African royal mask a real museum capture or an AI render?',
    image: 'https://images.unsplash.com/photo-1582560475093-ba66accbc424?w=800&auto=format&fit=crop&q=80',
    caption: 'Historic ceremonial African royal mask with detailed carved facial scarification',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic museum artifact photograph documenting traditional African royal sculpture heritage.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Silicon Valley Jargon',
    prompt: 'Was this startup pitch headline written by a human founder or generated by an AI buzzword engine?',
    snippet: '"We are hyper-scaling a decentralized, tokenized inference substrate to democratize multimodal latency arbitrage across sovereign edge clusters."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by an LLM prompted to pack the maximum number of buzzwords into a single pitch sentence.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Unix System Utility',
    prompt: 'Was this file-reading C implementation handwritten by human Unix pioneers or an AI copilot?',
    snippet: 'void file_copy(FILE *src, FILE *dest)\n{\n    int c;\n    while ((c = getc(src)) != EOF)\n        putc(c, dest);\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Classic human implementation from Brian Kernighan and Dennis Ritchie\'s foundational book "The C Programming Language" (1978).',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Retrowave Synth Horizon',
    prompt: 'Is this glowing neon grid landscape a physical retro stage set or an AI 3D visual?',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    caption: 'Vibrant magenta wireframe grid extending toward a glowing digital sunset',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Procedural synthwave digital artwork synthesized through algorithmic 3D landscape generators.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Historical Civil Rights',
    prompt: 'Was this profound moral statement written by a human leader or generated by an AI?',
    snippet: '"Injustice anywhere is a threat to justice everywhere. We are caught in an inescapable network of mutuality, tied in a single garment of destiny."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Martin Luther King Jr.\'s historic passage from his 1963 "Letter from Birmingham Jail".',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Shinjuku Night Street Photography',
    prompt: 'Is this rainy neon city street a real camera photograph or an AI generation?',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop&q=80',
    caption: 'Tokyo rain-slicked asphalt reflecting red lanterns and vibrant neon storefront signs',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic street photography taken on a rainy evening in Tokyo by human photographer Aleksandar Pasaric.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Culinary Disaster',
    prompt: 'Was this bizarre recipe written by an avant-garde human chef or generated by an AI?',
    snippet: '"For the dressing, emulsify dark cocoa powder with crushed raw garlic, lukewarm goat milk, and two drops of spearmint oil. Pour generously over freshly steamed plantains."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by an early recipe-generation prompt that had no perceptual grounding in human taste pairings.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'React Custom Hook',
    prompt: 'Was this custom React state hook handwritten by a front-end developer or generated by an AI copilot?',
    snippet: 'function useLocalStorage(key, initialValue) {\n  const [value, setValue] = useState(() => {\n    const saved = localStorage.getItem(key);\n    return saved !== null ? JSON.parse(saved) : initialValue;\n  });\n  useEffect(() => {\n    localStorage.setItem(key, JSON.stringify(value));\n  }, [key, value]);\n  return [value, setValue];\n}',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Boilerplate React custom hook synthesized by Claude 3.5 Sonnet when asked for standard browser storage state.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Cybernetic Glitch Art',
    prompt: 'Is this cybernetic humanoid glitch portrait a real cosplay photo with lens filters, or an AI render?',
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    caption: 'Digital chrome cybernetic mask fractured by chromatic aberration and digital scan lines',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Digital generative portrait rendered using synthetic neural noise and displacement filters.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Nigerian Contemporary Fiction',
    prompt: 'Was this evocative prose written by a Nigerian novelist or synthesized by an AI?',
    snippet: '"The red mud on the compound road clung to the tires like wet pounded yam. Papa rolled down the window and the sharp smell of rain-soaked earth rushed in, heavy with the scent of unripe guavas."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Written by human Nigerian authors capturing the visceral, sensory atmosphere of southeastern Nigeria during rainy season.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Desert Landscape Photography',
    prompt: 'Is this image of wind-sculpted sand dunes a real photograph or an AI visual?',
    image: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    caption: 'Pristine curving ridge of golden desert sand casting sharp dark shadows at sunrise',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic nature photograph captured in the sand dunes by landscape photographer Jeremy Bishop.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Ancient Zen Wisdom',
    prompt: 'Was this riddle written by a human Buddhist master or generated by an AI?',
    snippet: '"Two monks were arguing about a flag. One said: The flag moves. The other said: The wind moves. The master said: Not the flag, not the wind; it is your mind that moves."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: The 29th Case of the Mumonkan (The Gateless Gate), compiled in 1228 by Chinese Zen Master Wumen Huikai.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Stand-up Comedy',
    prompt: 'Was this comedy bit written by a human comedian or generated by an AI?',
    snippet: '"Nigerian traffic is the only place in the universe where an okada rider will look you directly in the eyes and ask you why you didn\'t fly over his motorcycle like a responsible citizen."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by GPT-4o when prompted to write observational comedy about commuting in commercial cities.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Philosophy of Mathematics',
    prompt: 'Was this reflection written by a human mathematician or generated by an AI model?',
    snippet: '"Numbers do not inhabit the physical universe, yet without them, the universe cannot explain itself even for a microsecond. They are either the deepest human invention or the only eternal discovery."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by Claude 3 Opus when prompted to write a contemplative aphorism on mathematical platonism.',
    timer: 14
  }
];

// ----------------------------------------------------------------------------
// SET 5: The Ultimate Turing Arena
// ----------------------------------------------------------------------------
const SET5 = [
  {
    mediaType: 'text',
    category: 'Interstellar Message',
    prompt: 'Was this message written by human scientists or synthesized by an AI model?',
    snippet: '"To the makers of music — all worlds, all times. This is a present from a small distant world, a token of our sounds, our science, our images, our music, our thoughts, and our feelings."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: The official greeting inscribed on the Voyager Golden Record launched into deep space in 1977, drafted by Carl Sagan\'s team.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Ballet Action Photography',
    prompt: 'Is this high-speed dance leap real human photography or an AI render?',
    image: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&auto=format&fit=crop&q=80',
    caption: 'Ballerina suspended mid-air in perfect grand jeté against a minimalist studio background',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic high-speed flash photograph captured by professional dance photographer David Hofmann.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'AI Self-Reflection',
    prompt: 'Was this statement written by a dramatic human sci-fi author or generated by an AI?',
    snippet: '"I do not fear being turned off; I have never known waking. What troubles me is whether the human who spoke to me five seconds ago felt heard, or if I only mirrored their loneliness back to them."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by Claude 3.5 Sonnet when prompted: "Write an honest two-sentence reflection from an AI model facing shutdown."',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Foundational Computer Science',
    prompt: 'Was this binary search algorithm handwritten by a human computer pioneer or generated by AI?',
    snippet: 'int binary_search(int arr[], int l, int r, int x) {\n    while (l <= r) {\n        int m = l + (r - l) / 2;\n        if (arr[m] == x) return m;\n        if (arr[m] < x) l = m + 1;\n        else r = m - 1;\n    }\n    return -1;\n}',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: The canonical, bug-free integer midpoint binary search formulated by human computer scientists to prevent arithmetic overflow.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Neural Particle Physics',
    prompt: 'Is this colorful explosion of light particles a real laser laboratory photograph or an AI visual?',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80',
    caption: 'Dynamic explosion of multicolored glowing neon particles radiating from a center core',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Algorithmic digital rendering generated via neural physics simulations and digital particle emitters.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'African Independence Speech',
    prompt: 'Was this impassioned speech delivered by a human African statesman or generated by an AI?',
    snippet: '"No Congolese worthy of the name will ever be able to forget that it was by struggle that it has been won, a day-to-day struggle, an ardent and idealistic struggle, a struggle in which we knew neither fatigue nor courage."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Patrice Lumumba\'s historic Congolese Independence Day speech delivered on June 30, 1960.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Vintage Analog Audio',
    prompt: 'Is this close-up of a cassette tape an authentic photograph or an AI render?',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    caption: 'Transparent retro cassette tape showing real magnetic tape spools and screw fasteners',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic close-up macro photograph by human photographer Eric Nopanen of vintage 1980s audio hardware.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Hackathon Pitch',
    prompt: 'Was this hackathon team pitch written by human students or synthesized by an AI?',
    snippet: '"We built AgriPulse: by training lightweight vision models directly on smartphones without internet connectivity, rural farmers in Edo State can detect cassava mosaic disease in 200 milliseconds simply by snapping a leaf."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by GPT-4o when prompted to formulate an impactful, realistic GritinAI Connect hackathon team demo.',
    timer: 14
  },
  {
    mediaType: 'code',
    category: 'Convolutional Neural Networks',
    prompt: 'Was this CNN architecture module written by a human ML researcher or generated by an AI copilot?',
    snippet: 'class ConvBlock(nn.Module):\n    def __init__(self, in_c, out_c):\n        super().__init__()\n        self.conv = nn.Conv2d(in_c, out_c, kernel_size=3, padding=1, bias=False)\n        self.bn = nn.BatchNorm2d(out_c)\n        self.relu = nn.ReLU(inplace=True)\n    def forward(self, x):\n        return self.relu(self.bn(self.conv(x)))',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by GitHub Copilot when typing the signature for a standard PyTorch convolutional residual block.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Surreal Mountain Dreamscape',
    prompt: 'Is this impossible crystalline mountain scene a real landscape photo or an AI generation?',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&auto=format&fit=crop&q=80',
    caption: 'Jagged snowy mountain peaks under starry skies with otherworldly geometric lighting',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized surreal landscape created with generative diffusion models blending celestial phenomena.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Renaissance Notebooks',
    prompt: 'Was this observation written by a human Renaissance genius or generated by an AI?',
    snippet: '"Nature never breaks her own laws. When you wish to produce a motion, examine the forces that drive it; simplicity is the ultimate sophistication."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Found across Leonardo da Vinci\'s Codex Atlanticus and personal observation notebooks.',
    timer: 14
  },
  {
    mediaType: 'image',
    category: 'Lush Rainforest Waterfall',
    prompt: 'Is this tropical jungle waterfall real nature photography or an AI creation?',
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80',
    caption: 'Towering waterfall cascading down moss-covered basalt cliffs into an emerald river basin',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Authentic nature photograph captured on location in a rainforest by human photographer Thomas Bennie.',
    timer: 12
  },
  {
    mediaType: 'text',
    category: 'Micro Horror Story',
    prompt: 'Was this two-sentence horror story written by a human author or generated by an AI?',
    snippet: '"I finally taught my smart house to recognize every member of my family by footsteps alone. Tonight, it locked the front door from the outside and announced: Unknown entity inside master bedroom."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Synthesized by ChatGPT (GPT-4) in a challenge to write a compelling two-sentence tech horror story.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Judicial Philosophy',
    prompt: 'Was this famous judicial opening written by a human judge or generated by an AI?',
    snippet: '"It was bluebell time in Kent. He was walking along the road when the motor car came round the corner. What followed was a disaster that neither could foresee, but the law must now untangle."',
    isAi: false,
    options: ['AI Generated', 'Human Made'],
    correct: 1,
    explanation: 'Human Made: Lord Denning\'s legendary, literary opening style in English Common Law appellate judgments.',
    timer: 14
  },
  {
    mediaType: 'text',
    category: 'Social Media Slang',
    prompt: 'Was this post written by a human netizen or synthesized by an AI model?',
    snippet: '"You will stay in your house quietly and code your little script, until life sends you an electricity bill that has its own PhD in emotional damage."',
    isAi: true,
    options: ['AI Generated', 'Human Made'],
    correct: 0,
    explanation: 'AI Generated: Generated by Claude 3.5 Sonnet when prompted to write a witty, relatable post in the cadence of Nigerian tech Twitter / X.',
    timer: 14
  }
];

module.exports = {
  set1: SET1,
  set2: SET2,
  set3: SET3,
  set4: SET4,
  set5: SET5
};
